# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(null=True, upload_to='images/<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='event',
            name='other',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
